### ISSUE TITLE
Allow for a way to have unimplemented functions in base class without requiring `check_signature=False`

### ISSUE THREAD

**Issue by AkshitaB** [mkorpela/overrides#87] opened 2021-05-25 23:20 UTC
In the latest `overrides` version (`6.1.0`), the following code snippet leads to errors:

```
class A:
    def generic_func(self, *args, **kwargs):
        raise NotImplementedError

class B(A):
     @overrides
    def generic_func(self, actual_arg, some_kwarg=1):
        .
        .
        .
```

It can be pain to require setting `@overrides(check_signature=False)` if several classes in the code inherit from a class like `A`. Is there a way to ignore the check for `*args` and `**kwargs`?

**Comment by ashwin153** [comment] 2021-05-25 23:49
In order for `B` to be a subclass of `A`, `generic_func` must be callable on instances of `B` as if they were instances of `A`. While `a.generic_func(some_random_arg=1)` is completely valid if you were to call `b.generic_func(some_random_arg=1)` you would get an error at runtime. In order to fix this problem, simply change the signature of `B.generic_func` to `def generic_func(self, actual_arg, *args, some_kwarg=1, **kwargs)`.

**Comment by AkshitaB** [comment] 2021-05-25 23:56
@ashwin153 Yes, I should have mentioned this in the original issue. While it's possible to add `args` and `kwargs` to avoid the error, the underlying problem of having to change this at a lot of places remains. For instance - PyTorch code; where several modules inherit from `torch.nn.Module` and override the `forward` method. 

While I agree that having `args` and `kwargs` explicitly mentioned is cleaner; the use case is often having a generic base class method that allows for any number of inputs, and the inherited method to have restricted, specific inputs.

**Comment by mkorpela** [comment] 2021-05-26 03:10
@AkshitaB thanks for reporting.
Version 6.1.0 should ignore third party modules that are untyped. I would assume this is also true for torch in case of allenlp

**Comment by mkorpela** [comment] 2021-05-26 04:51
```Python
❯ python
Python 3.9.1 (default, Feb 13 2021, 16:06:40)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch.nn as nn
>>> from overrides import overrides
>>> class Model(nn.Module):
...     @overrides
...     def forward(self, x):
...             return None
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in Model
  File "/Users/mkorpela/workspace/overrides/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/Users/mkorpela/workspace/overrides/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/Users/mkorpela/workspace/overrides/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/Users/mkorpela/workspace/overrides/overrides/signature.py", line 93, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/Users/mkorpela/workspace/overrides/overrides/signature.py", line 287, in ensure_return_type_compatibility
    raise TypeError(
TypeError: Model.forward: return type `None` is not a `<class 'NoneType'>`.
```
So we have a bug here. Thanks @AkshitaB !

**Comment by mkorpela** [comment] 2021-05-26 04:53
Seems that torch.nn.Module does some really funny stuff: https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module
```Python
# Trick mypy into not applying contravariance rules to inputs by defining
# forward as a value, rather than a function.  See also
# https://github.com/python/mypy/issues/8795
def _forward_unimplemented(self, *input: Any) -> None:
    r"""Defines the computation performed at every call.

    Should be overridden by all subclasses.

    .. note::
        Although the recipe for forward pass needs to be defined within
        this function, one should call the :class:`Module` instance afterwards
        instead of this since the former takes care of running the
        registered hooks while the latter silently ignores them.
    """
    raise NotImplementedError
```

**Comment by mkorpela** [comment] 2021-05-26 04:54
So the problem is that overrides was not "tricked" by that.

**Comment by mkorpela** [comment] 2021-05-26 04:57
https://github.com/python/mypy/issues/8795
Guido states that you should explicitly ignore type check in this case in the subclasses.

**Comment by mkorpela** [comment] 2022-10-09 13:57
Closing as does not result into an action.

**Closed by mkorpela** 2022-10-09 13:57 UTC
